### ISSUE TITLE
Wrong usage of datum labels

### ISSUE THREAD

**Issue by jcubic** [biwascheme/biwascheme#234]
Here is example:
```scheme
(let ((x (cons 1 2))) (list x x))
;; ==> (#0=(1 . 2) #0#)
```
it should be printed as:
```
((1 . 2) (1 . 2)
```
This is how it works in every Scheme I was testing (Kawa, Guile, Gambit, Gauche).

**Comment by yhara** [comment]
Hmm, this is interesting.

R7RS does not specify the output of REPL so I think this behavior is "allowed".
However it seems like we should just use `write` instead of `write/ss` here. I thought `write` does not support infinite list, but I found R7RS small says it must stop for circular objects.
So once #236 is fixed, we can use `write` here and the output will be the same as other Schemes.
