### ISSUE TITLE
(define fs (js-eval "require('fs')")) does not work

### ISSUE THREAD

**Issue by mjobuda** [biwascheme/biwascheme#275]
`biwascheme> (define fs (js-eval "require('fs')"))
ReferenceError: require is not defined [js-eval]
`

**Comment by yhara** [comment]
Confirmed with git master and this was working on biwascheme 0.7.1.

```
/Users/yhara/Dropbox/proj/biwascheme % biwas
BiwaScheme version 0.7.1
try (+ 1 2), etc. (Ctrl-D to exit)
biwascheme> (define fs (js-eval "require('fs')"))
#<undef>
```

**Comment by yhara** [comment]
@mjobuda by the way, you can use `node-require` for that purpose.
```scheme
(define fs (node-require "fs"))
```

**Comment by mjobuda** [comment]
Thank you yhara! Yes, I also figured that out, but that does not change the fact that it's a bug. Either in the implementation or in the documentation. The problem with scheme is that due to their low user base the implementations are not mature. In order to be usable in production all small issues like this have to be fixed and/or described. I would really love to have a useable Scheme/lisp in the browser!! The only one that seems to become acceptable is ClojureScript. And I have a problem with clojurescript. The userbase is 99% react centric. And while I love lisps I hate facebook from deep in my heart and am also disgusted by completly unnecessary React codebloat. So I'd rather stay away from these people. Biwa scheme seems looks really nice. It could be usable.

**Comment by tmccary9207** [comment]
I looked a bit into this issue. This appears to be a CommonJS (which has require defined) and ESModules (which doesn't) problem. The solution of using the `node-require` function seems to be a good enough solution. Using something like `new Function` would work in a NodeJS environment, would not work in a browser environment (due to CSP). Since Javascript's eval only works on strings and can not be passed parameters it is not possible to inject things like require into it. Unless I am missing something that would inject require into the environment of eval I don't see a possible route that would fix this. However, there is the option of making the NodeJS version use some form of eval that would use `new Function` and inject Node specific variables into the function. A possible implementation would be something like below I presume.

```js
define_libfunc("js-eval", 1, 1, function (ar) {
  const func = new Function(`{ return function ({ require }) { return ar[0] } }`);
  return func.call().call(null, { require });
});
```

**Comment by yhara** [comment]
This "bug" was introduced by c0eee4bed907767ac4eb2551a84d8168ed3d0586, which fixes the following warning from rollup:

```
$ rollup -c
...
(!) Use of eval is strongly discouraged
https://rollupjs.org/guide/en/#avoiding-eval
src/library/js_interface.js
23:
24: define_libfunc("js-eval", 1, 1, function(ar){
25:   return eval(ar[0]);
             ^
26: });
27: define_libfunc("js-ref", 2, 2, function(ar){
```

At that time I did not realized that this causes incompatibility. I've temporally reverted this patch and will release v0.7.5 to keep backward-compatibility in v0.7.x.
However at some point in the future (maybe v0.8) I'd like to apply the patch again to suppress this annoying warning.

**Comment by jcubic** [comment]
This is a hack, but you can try to create `@biwascheme/eval` package and import it. Maybe rollup will be happy with this. Or maybe just find a small existing utility that uses eval, like leftpad that was few lines of code.

**Comment by yhara** [comment]
> This is a hack, but you can try to create @biwascheme/eval package and import it. Maybe rollup will be happy with this. Or maybe just find a small existing utility that uses eval, like leftpad that was few lines of code.

That's an interesting idea. I've tried it, but rollup seems to check all the bundled code, including imported ones.
https://gist.github.com/yhara/07a9dfc003a503cf4a6d32e46677501b

> (!) Use of eval is strongly discouraged
https://rollupjs.org/guide/en/#avoiding-eval
src/bs_eval/index.mjs
1: function bs_eval(s){
2:   return eval(s);
            ^
3: }
4: export default bs_eval;
