### ISSUE TITLE
"\\n" not parsed correctly & licensing issues regarding /system/parser.js

### ISSUE THREAD

**Issue by GeethanPfeifer** [biwascheme/biwascheme#307]
`"\\n"` is parsed as `"\\\n"`
This is also true of any string where "\n" appears but the \ before the n is escaped itself.
You can test this also by inputting: `(display "\\n")` into the REPL.

**Comment by GeethanPfeifer** [comment]
I have also written a fix [here](https://github.com/biwascheme/biwascheme/pull/308) though I recommend at some point the parser should be rewritten entirely.

**Comment by jcubic** [comment]
@yhara if you want to look into a nice tokenizer that is easy to modify. You can look at my LIPS Scheme project. The tokenizer can be extracted, look into a [`Lexer` class](https://github.com/jcubic/lips/blob/master/src/lips.js#L995) and [`Lexer._rules`](https://github.com/jcubic/lips/blob/master/src/lips.js#L1257). It's a simple state machine (unfortunately the whole library is in one file, I was not able to split it into modules, because of cyclic dependencies).

**Comment by GeethanPfeifer** [comment]
Upon further analysis of the parser code I have realized that the jsScheme, which the parser uses code from, is licensed under the GNU GPL. I believe that this license requires the entirety of biwascheme to be licensed under the GNU GPL if it uses it. Thus, I believe that in order for biwascheme to not violate the GNU GPL, either the parser as a whole needs to be replaced (perhaps with the one from jcubic's LIPS), or the project needs to be re-licensed under the GNU GPL.

I have closed my pull request as I don't wish to make major changes to the licensing of the project by myself, but if biwascheme chooses to go down that route my version of biwascheme with this issue patched is located here: https://github.com/GeethanPfeifer/biwascheme . Note that I have changed the license of this repository to comply with the GNU GPL.

All the best,

Geethan
