### ISSUE TITLE
How to deal with numbers?

### ISSUE THREAD

**Issue by viebel** [biwascheme/biwascheme#68]
Please give me a couple of code examples of how to deal with:

-  complex numbers
- rational numbers
- infinity
- inexact numbers
- etc...

**Comment by yhara** [comment]
Unfortunately, rational numbers and exactness are not implemented. I'm willing to implement rational if someone requested, but exactness is hard to implement on JavaScript because you need to wrap every number with JavaScript Object.

Complex numbers are only partially implemented. You can create complex numbers like this, but you cannot do some calculations with them because I forgot to fix `+`, `-`, etc. to support them (thanks for remind me of that).

```scm
(define c1 (make-rectangular 1 2))
(real-part c1) ;=> 1
(imag-part c1) ;=> 2
(define c2 (make-polar 1 3.14))
(magnitude c2) ;=> 1
(angle c2) ;=> 3.1400000000000428
```

Here is an example to deal with infinite numbers (and NaN).

```scm
(/ 1 0) ;=> +inf.0
(infinite? (/ 1 0)) ;=> #t
(infinite? 123)  ;=> #f
(finite? 123) ;=> #t

(nan? (/ 0 0)) ;=> #t
```

**Comment by viebel** [comment]
What should be done to implement rational and to fix arithmetic operations for complex numbers?
If you guide me, I'd be happy to open a PR.

**Comment by yhara** [comment]
Okay here are some pointers.

- Arithmetic functions like "+" are defined in https://github.com/biwascheme/biwascheme/blob/master/src/library/r6rs_lib.js
- class Complex is defined in https://github.com/biwascheme/biwascheme/blob/master/src/system/number.js

**Comment by viebel** [comment]
Thanks. Will look at it.
Do you know what `(define infinity (/ 1 0))` causes an error?

**Comment by yhara** [comment]
> Do you know what (define infinity (/ 1 0)) causes an error?

Oh really? On which environment did you try?

**Comment by viebel** [comment]
on klipse

**Comment by viebel** [comment]
I have opened a PR #69 for complex numbers arithmetics.

**Comment by yhara** [comment]
@viebel Thanks, I've merged it. You can implement rational numbers arithmetics by the same way (you see class Rational defined in numbers.js).

> on klipse

Looks like working fine:

1. Open http://blog.klipse.tech/scheme/2016/09/11/scheme-tutorial-1.html
1. Type `(define infinity (/ 1 0))` in the first input form (in the section "Boolean")
1. `#<undef>` is shown as a result, because `define` itself does not evaluates to a value.
1. When I changed the code to `(define infinity (/ 1 0)) infinity`, `Infinity` is shown as a result.

> Here is an example to deal with infinite numbers (and NaN).

Sorry this example was wrong. You can't divide a number by 0 according to r7rs.pdf. Instead, you can get a infinity with `+inf.0`.

```scm
(infinite? +inf.0) ;=> #t
(infinite? 123)  ;=> #f
(finite? 123) ;=> #t
(nan? +nan.0) ;=> #t
```

**Comment by viebel** [comment]
Thanks for the clarifications.
Could you release a new version, so I can include examples of complex numbers in my blog post?

**Comment by viebel** [comment]
Also, would you like to write a blog post with interactive Scheme code snippets using biwascheme and klipse?

**Comment by yhara** [comment]
@viebel Released https://github.com/biwascheme/biwascheme/releases/tag/0.6.5

**Comment by yhara** [comment]
> Also, would you like to write a blog post with interactive Scheme code snippets using biwascheme and klipse?

Sorry I can't take time now because I'm going on a trip next week.
I've added a link to klipse on biwascheme.org.

**Comment by viebel** [comment]
Thanks for the link to klipse.
Might be better to have a link to the blog post. It's more interactive!

**Comment by yhara** [comment]
Updated! http://www.biwascheme.org/
