### ISSUE TITLE
Better ajax support with error handling and arbitrary body

### ISSUE THREAD

**Issue by amirouche** [biwascheme/biwascheme#96]
I created a [custom `ajax-post` procedure](https://framagit.org/a-guile-mind/azul/commit/920a676b85323b427741a7c07ad28aedc97b9fd9) that allows to post an arbitrary string body. I don't want to use `http-request` which makes things complicated backend side. I want to send scheme values as strings.

Also, it would be nice to have exception support to handle error cases.

WDYT?

**Comment by yhara** [comment]
There should be a way to specify entire post body. But I'd prefer extending existing function rather than adding a new one.

So how about this?

```
(http-post path alist)  ; The existing API
(http-post path string) ; Specify the post body directly by `string`
```

For error cases, it is difficult to support them with exceptions because BiwaScheme does not have exception handling features right now. However, it is easy to extend `http-post` to return error value.

```
(http-post path str) ;=> Return string (response body) when succeeded
(http-post path str) ;=> Return something like '(404 "<h1>Not Found</h1>") for error cases
```

**Comment by amirouche** [comment]
> it is easy to extend `http-post` to return error value.

Indeed. That is what I will do.

It is unclear to me whether `biwascheme.js` should offer (deep) integration with the browser or nodejs. The alternative I have in mind is good Scheme support with great FFI. The latter is already the case in my opinion.
